const express=require('express');const path=require('path');
const app=express();app.use(express.json({limit:'12mb'}));app.use(express.static(__dirname));
const key=process.env.GEMINI_API_KEY||process.env.GOOGLE_API_KEY||'';
const textModel=process.env.GEMINI_TEXT_MODEL||'gemini-3.8-flash';
const imageModelDefault=process.env.GEMINI_IMAGE_MODEL||'gemini-3.1-flash-image';
const port=process.env.PORT||3000;
async function gemini(model, body){if(!key)throw new Error('GEMINI_API_KEY belum dikonfigurasi pada server');const r=await fetch('https://generativelanguage.googleapis.com/v1beta/models/'+encodeURIComponent(model)+':generateContent',{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':key},body:JSON.stringify(body)});const t=await r.text();let d;try{d=JSON.parse(t)}catch{d={raw:t}}if(!r.ok)throw new Error((d.error&&d.error.message)||('Gemini HTTP '+r.status));return d}
app.get('/api/health',(req,res)=>res.json({ok:true,engine_version:'2.0.0',model:textModel,capability_pack:'2.0.0',gemini_key_configured:Boolean(key)}));
app.post('/api/generate',async(req,res)=>{try{const x=req.body||{};const system='Anda adalah Rumah Guru AI. Buat dokumen pendidikan Indonesia yang sistematis, kontekstual, operasional, formal, dan siap dipetakan ke template. Pastikan tujuan, kegiatan, LKPD, asesmen, dan rubrik selaras. Kembalikan JSON valid saja dengan key: title, subtitle, tujuan, kompetensi_awal, pemantik, kegiatan, lkpd, asesmen, rubrik.';const prompt=system+'\\nData: '+JSON.stringify(x);const d=await gemini(textModel,{contents:[{role:'user',parts:[{text:prompt}]}],generationConfig:{responseMimeType:'application/json'}});const raw=d.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('')||'{}';let result;try{result=JSON.parse(raw)}catch{result={title:x.document_type||'Dokumen',tujuan:raw}}res.json({ok:true,model:textModel,result})}catch(e){res.status(500).json({ok:false,error:e.message})}});
app.post('/api/image',async(req,res)=>{try{const x=req.body||{};const model=x.model||imageModelDefault;const prompt=(x.prompt||'').trim()+'\\nRasio aspek: '+(x.ratio||'1:1')+'. Gunakan gaya edukatif yang rapi dan aman.';const d=await gemini(model,{contents:[{role:'user',parts:[{text:prompt}]}],generationConfig:{responseModalities:['TEXT','IMAGE']}});const parts=d.candidates?.[0]?.content?.parts||[];const img=parts.find(p=>p.inlineData||p.inline_data);const data=img?.inlineData||img?.inline_data;if(!data) return res.status(502).json({ok:false,error:'Model tidak mengembalikan gambar.'});res.json({ok:true,model,image_base64:data.data,mime_type:data.mimeType||data.mime_type||'image/png'})}catch(e){res.status(500).json({ok:false,error:e.message})}});
app.listen(port,()=>console.log('Rumah PPM & LKPD AI on '+port));